-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.leads (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  tenant_id uuid NOT NULL,
  visitor_id text NOT NULL,
  source_type text NOT NULL DEFAULT 'web_chat'::text CHECK (source_type = ANY (ARRAY['web_chat'::text, 'whatsapp'::text, 'form'::text, 'backoffice'::text])),
  operacion text CHECK (operacion = ANY (ARRAY['venta'::text, 'alquiler'::text])),
  zona text,
  presupuesto_max numeric CHECK (presupuesto_max >= 0::numeric),
  nombre text,
  contacto text,
  summary text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'owner'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'agent'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zp_posting_pictures (
  id bigint NOT NULL DEFAULT nextval('zp_posting_pictures_id_seq'::regclass),
  posting_id text NOT NULL,
  order integer,
  url_730 text,
  url_360 text,
  title text,
  width integer,
  height integer,
  multimedia_type_id text,
  tenant_id uuid NOT NULL,
  CONSTRAINT zp_posting_pictures_pkey PRIMARY KEY (id),
  CONSTRAINT zp_posting_pictures_posting_id_fkey FOREIGN KEY (posting_id) REFERENCES public.zp_postings(id),
  CONSTRAINT zp_posting_pictures_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.zp_postings (
  id text NOT NULL,
  source text NOT NULL DEFAULT 'zonaprop'::text,
  posting_code text,
  url text NOT NULL UNIQUE,
  title text,
  operation_type text,
  operation_type_id text,
  price_amount numeric,
  price_currency text,
  expenses_amount numeric,
  expenses_currency text,
  real_estate_type text,
  real_estate_type_id text,
  description text,
  address_name text,
  location_id text,
  location_name text,
  city_name text,
  state_acronym text,
  country_name text,
  latitude double precision,
  longitude double precision,
  status text,
  posting_type text,
  premier boolean,
  publisher_id text,
  publisher_name text,
  publisher_url text,
  publisher_type_id text,
  publisher_slug text,
  publisher_premier boolean,
  whatsapp text,
  modified_date timestamp with time zone,
  inserted_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  main_features jsonb,
  general_features jsonb,
  development_features jsonb,
  highlighted_features jsonb,
  flags_features jsonb,
  raw_json jsonb NOT NULL,
  tenant_id uuid NOT NULL,
  CONSTRAINT zp_postings_pkey PRIMARY KEY (id),
  CONSTRAINT zp_postings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);