-- Clean LEADS table (Supabase/Postgres) + multi-tenant
-- No triggers

drop table if exists public.leads cascade;

create table public.leads (
  id bigint generated by default as identity primary key,

  -- multi-tenant
  tenant_id uuid not null references public.tenants(id) on delete cascade,

  -- who / where the lead came from
  visitor_id text not null, -- e.g. widget session id, whatsapp phone, form session, etc.
  source_type text not null default 'web_chat'
    check (source_type in ('web_chat', 'whatsapp', 'form', 'backoffice')),

  -- lead fields
  operacion text null check (operacion in ('venta', 'alquiler')),
  zona text null,
  presupuesto_max numeric null check (presupuesto_max >= 0),
  nombre text null,
  contacto text null,
  summary text null,

  -- timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- indexes (common queries)
create index if not exists leads_tenant_created_idx
  on public.leads (tenant_id, created_at desc);

create index if not exists leads_tenant_visitor_created_idx
  on public.leads (tenant_id, visitor_id, created_at desc);

create index if not exists leads_tenant_source_type_created_idx
  on public.leads (tenant_id, source_type, created_at desc);

create index if not exists leads_tenant_operacion_idx
  on public.leads (tenant_id, operacion);
